---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: root
    tasks:
      - name: ensure apache is at the latest version
        apt:
          name: apache2
          state: latest
      - name: ensure apache is running
        service:
          name: apache2
          state: started
